/** 掲載プランのマスタ（seed / 初回アクセス時の自動投入で共有） */
export const MASTER_LISTING_PLANS = [
  {
    name: "FREE",
    rank: 0,
    price1month: 0,
    price3months: 0,
    price6months: 0,
    price12months: 0,
    maxPhotos: 10,
    hasTournament: false,
    description:
      "店舗ページを無料・無期限で掲載。検索優先やトップのイベント枠などの強化露出は対象外",
    sortOrder: 0,
    isActive: true,
  },
  {
    name: "BASIC",
    rank: 1,
    price1month: 5000,
    price3months: 14250,
    price6months: 27000,
    price12months: 51000,
    maxPhotos: 10,
    hasTournament: true,
    description:
      "無料掲載に加え、検索・一覧での露出強化・トーナメント掲載など（プラン範囲に準じます）",
    sortOrder: 10,
    isActive: true,
  },
  {
    name: "PREMIUM",
    rank: 2,
    price1month: 12000,
    price3months: 34200,
    price6months: 64800,
    price12months: 122400,
    maxPhotos: 30,
    hasTournament: true,
    hasAnalyticsKeyword: true,
    maxSubAccounts: 2,
    description:
      "露出強化に加えトーナメント掲載など。検索・イベント枠の扱いはプラン範囲に準じます",
    sortOrder: 20,
    isActive: true,
  },
  {
    name: "PLATINUM",
    rank: 3,
    price1month: 25000,
    price3months: 71250,
    price6months: 135000,
    price12months: 255000,
    maxPhotos: 100,
    hasTournament: true,
    hasAnalyticsKeyword: true,
    hasAnalyticsCompetitor: true,
    maxSubAccounts: 10,
    description:
      "最も手厚い検索・イベント露出と拡張機能（プラン範囲に準じます）",
    sortOrder: 30,
    isActive: true,
  },
] as const;
